# Site
repository: yeeyangtee/yeeyangtee.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yee Yang Tee
title: Deep Learning and AI Consultant
email: yeeyangtee@gmail.com
website: https://www.yeeyangtee.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: yeeyangtee
github_username:  yeeyangtee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: teeletubby
linkedin_username: teeyeeyang
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-6600-0685

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/portrait_compress_1.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, Yee Yang here and I'm a professional AI and Deep Learning consultant. I am currently a final year PhD student at NTU Singapore, specializing in Computer Vision research.

  I am most skilled in <mark>PyTorch</mark> and <mark>Toothbrushing</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pluribus Poker AI Bot
        link: github.com/yeeyangtee
        # link_text: Project Website
        additional_links:
          - title:  yeeyangtee/pluribus
            icon: fab fa-github
            url: github.com/yeeyangtee/pluribus
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Poker playing bot from Facebook
        description: | # this will include new lines to allow paragraphs
          I worked on this projet as a means to learn about reinforcement learning, and hopefully earn some money if it succeeded. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: inspections.ai
        link: mapgage.com
        link_text: inspections.ai
        sub_title: Chief Technology Officer
        caption: Jan 2020 - Present
        quote: >
          Data is the new oil, and we are the drillers.
        description: | # this will include new lines to allow paragraphs
          inspections.ai develops " Visual-AI-as-a-service", using AI in smart cameras to extract operational data from video streams. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nanyang Technological University
        caption: 2020 - Present
        sub_title: PhD in Electrical and Electronic Engineering 
        quote: >
          A research-intensive public university, Nanyang Technological University, Singapore (NTU Singapore) has 33,000 undergraduate and postgraduate students in the Engineering, Business, Science, Medicine, Humanities, Arts, & Social Sciences, and Graduate colleges.
        description: | # this will include new lines to allow paragraphs
          I derped around daily with <mark>PyTorch</mark>
      - layout: left
        title: Nanyang Technological University
        caption: 2017 - 2020
        sub_title: BEng in Electrical and Electronic Engineering 
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time as an undergraduate in NTU, I was awarded the prestigious Nanyang Scholarship and the EEE Chair Award. I graduated with First Class Honours with a GPA of 4.89/5.0 and was awarded the Dean's List for AY 16/17, 17/18, 19/20.
          I was active as an EEE Outreach Ambassador, reaching out to prospective students and sharing my experiences as an EEE student. I managed logistics and budgeting for the National Vertical Marathon in 2017 and 2018, a stair climbing event with over 2,000 participants.
          In NTU, I had numerous opportunities to experience different cultures and travel the world: Silicon Valley Outreach Programme, Semester Exchange @ Czech Republic, Volunteering @ Remote village in Chiang Mai.

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and engineering, some of my other interests and hobbies are:
      - Scuba Diving
      - Hiking
      - Bouldering

      Look at this cool image  
      # ![Trees](images/landscape-tress.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
